CREATE TABLE finalDB (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_path VARCHAR(255),
    title TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
